coverage:
  notify:
    slack:
      default:
        url: secret:aRucoiC6Ru6+GPE5by+cEBJGJfodTA1YAjKzM8D7TWstV0cIG3FwjINgj1axivYJceRuBUkSkiBBSMIA4Iz+ZNY/7P7UkhIu7BiRxKu6ttZqo/xpokK/Y4CH74rJ5bWPANNQpQLZ4ThUwKS0TvTVeH0xGnar+a9OyS/LrW8KjQI=